services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test: ["CMD-SHELL","curl -f http://localhost:8082/actuator/health || exit 1"]
      timeout: 10s